apiVersion: batch/v1
kind: Job
metadata:
  name: grpc-client
spec:
  template:
    metadata:
      name: grpc-client
    spec:
      containers:
      - name: grpc-client
        image: grpc-client:1.0
        env:
        command: [ "/bin/sh", "-c", "./sbt \"runMain com.example.helloworld.GreeterClient Alice\"" ]
      restartPolicy: Never
