apiVersion: v1
kind: Service
metadata:
  labels:
    app: grpc-server
  name: grpc-server
spec:
  type: ClusterIP
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    app: grpc-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-server
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: grpc-server
  template:
    metadata:
      labels:
        app: grpc-server
    spec:
      containers:
      - name: grpc-server
        image: grpc-server:1.0
        ports:
        - containerPort: 8080
        imagePullPolicy: Never
      restartPolicy: Always

